# Exported from Render on 2024-06-18T15:11:29Z
services:
- type: web
  name: Marilinha-4
  runtime: docker
  repo: https://github.com/Testando0/Marilinha
  plan: free
  region: frankfurt
  dockerCommand: ./start.sh && ./main.sh
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeploy: false
version: "1"
